rules:
    disabled: [dependency-management]
    custom: []
git:
    maxFileSize: 10000000
code-quality:
    linters:
        - pylint
        - isort
testing:
    report: ""
    targets:
        minimum: 1
        ratio:
            tests: 1
            other: 4
    coverage:
        report: ""
        targets:
            line: 80