name: Continuous-integration

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python and Install requirements
      uses: ./.github/actions/python-setup
    - name: Run pylint
      run: pylint src
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python and Install requirements
      uses: ./.github/actions/python-setup
    - name: Obtain data
      run: |
        dvc repro
    - name: Test with pytest
      run: |
        coverage run --source=src -m pytest --junitxml=reports/test-results.xml --html=reports/test-results.html && coverage lcov
    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: success() || failure()        # run this step even if previous step failed
      with:
        name: test-results
        path: reports/test-results.xml
    - name: Coveralls
      uses: coverallsapp/github-action@v2
