name: Continuous-integration

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python and Install requirements
      uses: .github/workflows/python-setup.yml
    - name: Run pylint
      run: pylint src
    - name: Run dslinter
      run: pylint --load-plugins=dslinter src
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python and Install requirements
      uses: .github/workflows/python-setup.yml
    - name: Obtain data
      run: |
        dvc repro
    - name: Test with pytest
      run: |
        pytest tests --junitxml=reports/test-results.xml